### ISSUE TITLE
`tmp` folder being saved in result asset 

### ISSUE THREAD

**Issue by bjhardcastle** [AllenNeuralDynamics/aind-capsule-ephys-spikesort-kilosort25-full#12]
Hi @alejoe91,
I'm not sure if this a feature or a bug, but I noticed that recent assets have a copy of the raw data saved in `tmp`:
for example: [f822ac7c-a6f6-4b3d-ba2c-603937e6604e](https://codeocean.allenneuraldynamics.org/data-assets/f822ac7c-a6f6-4b3d-ba2c-603937e6604e/ecephys_681532_2023-10-17_14-01-23_sorted_2023-10-20_11-50-37?filters=N4IgZglgNgLgpgJxALhAQylEAaEBHAV0QE8UQ4BjOABwAtiBnAfQDYAOARgFYBmAJhwgGAewQwyAOzQBbOIIAmcBhRRgMDOLmpoA5nOQctiAAq79fAAy408gG5oJVeSlBTZLkBEdQCisgElvXzlceAAPcVRBSDgoeQAVYmp9EHDxXABrOGIAORkUtxDU4R0dKH01KA1cODDtCUVnZEqNAF9cRWUECGoYCGEJDy8KHz9UQJHgwTSyaIhYhKSUmczsvPdUTopu3v7B0JKyivVNcjqHRtUT9tTdBg8oCAZIgG0AXVxh0ZSJ77mFxLJMiPZ6CLK5fJkGB3aaHcpXKqnWr1S7Na64GJxJgWB5PV5nGAINBUTAEKBoBAAAlilEJwjojH6UBKpA%2BniCYxAvymGPmcUBKRB6RA4PWKWkwnkGAgMFIB1K8LRiJq5wacCahKIuHsPjgArIz26Eh0IBumPkTA4uNByHenw5Pwd-35S2BeLBa0hqC8zxlBD6A1hCuOyrOKPVCOqIB1RH1qENXhNZr5FoEyFAQpQdvZk053L8vIBrtQmdWEI2ICl0Mp5VssSDR0jSNVqJapxjeuLQkJidNhaxPCGTvGTtCtUiIGdiyBqBWIs9FYYBAARgArWmUiDOeWNpVR5EXCN7uDJhZMAAs1tebK%2BUxHuaK5rjIFL8-LKWRiAgsgkMEpsqBHdFTbFVwyaEDowwWMuwTY1TRuQoyEoGh6GYdhuH4JhLD4HgAFoOAsfCAHZLXPXCLA4XCcKYEQxHVLCLBw-DCMsS1KK4QieCI6YYVtcgqAZe4tAQYQqAYDRtxAdDeAENkMi8JoQAQJQyWFBgIAAL30FgLDYc8iJ4Cxzy4DiAE5eXKe4DA4UyCI6NBoQ0GArJeUAtzIUyWBYIjjL4PhcK4ZceDI-SLBYXC2DYPg4FwtRTLACwiKIjgnAEUIZUVfiUMYVhOBkhimII4jSPIyicMECUCF-JCBNQ3KML4Aq8KKjgSI4MiKKowdWjZZTqBE%2BQCAoCBl0VTVTmSBBpCedSBis0BbHmAB3FBxu1ZaAGVaApfRxpuZ4HJSSApCwXBhCWiREH8RTzw4HgWHkEzKPkHgKDw89lz4Mi2DARRyL4ChzzYOA0DAAiwG4s6LsQMUyDQBTKQ0BBFqoSlhDiQRthB%2BB5AAQUiDgWFMoi2EYlguIAOiIvg2HJu7cGXNANAAVQQLBUFoGAYGoBhkAAej5ihJTgUSQYkCmMHKCRLoIIk4mINwIAoBgKdEHQ%2BarJm4Gcvnbvux6uGe173s%2B77fpixjAeB0HwaIvmwCivhiSIihcLQFgwHCj6eHkXDGYB3CdJ4UyuLgLyjKKIXpGmmBrrIImLE8iwbDYIjTPPDO4DAfhzxsCgOAB7PjJYPhlyIz75B%2BigcVwBAqo27YegnIXFD5uv9hACg0B5sk4DjzZlyC%2BQKD4SjPqoXCPuJXDTL4F2qK4UzGOM88cK4zHu6Xcpn3U414VwLue-KDafBNVAiI4oniY3o%2B4Fh1AAAoDtGuAAEpKQAUUEyl%2BtF8TEx-j0WIXg4CUgANLQGELRGAfAKZcExsIaQ1B-QOT2P3Ssy4Q42ETrheQy5zwxQ%2BnAb655TJsFwjwNAFguCgwoF5LgREa7skUGEDa0J4BkCjtQcoONMYEGeIggAstrGwDk0AeE1jWOAdZ2aVi-HWeQlJNaCE-N0H8f4AIflqowCqkppSyjIB-CIRISQ%2BHJFSGkFA6SCSZCyQQS41wbncqgaS-A%2BwviZrHNUYQjyE2JqTHgnAWAU1MlwUmxMuDWCsRAOsAB5aGCAXJuRundB6T1cHG0nqbCK5t-pWxBmDCwENBCIVQPDBoiNEAo1AejSScBpDw1kTLOW8gFYyCVgwAAApLOAEgfR9BgP6OAqsEBJhvBIZBMAAAiYiszJI8l5HyXA-IBSCiFRh4VIrRVimgeKiVkqpWmBlLR2U0J5UwthZqhFWolU6uVXAlVqqoGQoJeq%2BVLnMWKu1UqXVTRsixodPGMAAAyaBlz1lQLEqxlJLDYBhYxHglIjLIA4oIckzxAgsPVKC8FsioV-lhfCnCSKuAGCYepLSOKIUgC4F5Cm7BKQAHEABCCDo4ynjkvJO4jPgMBmY5bWTZWhAA)

**Comment by alejoe91** [comment]
Hi Ben! Yep we noticed yesterday. Fixed it and pushed a new version. The problem was due to a mismatch in the aind-data-schema version, which was making the capsule failing when updating the processing.json
