### ISSUE TITLE
Change how max_bad_channel_fraction_to_remove works

### ISSUE THREAD

**Issue by egmcbride** [AllenNeuralDynamics/aind-capsule-ephys-spikesort-kilosort25-full#18]
Currently, probes are not sorted if at least 50% of channels are either dead, noisy, or out of brain. However, occasionally a probe may not be inserted very far into the brain for various reasons, which would lead to it not being sorted even if the channels in the brain are perfectly noise-free.

Could you change the threshold so that if there are at least ~50-100 channels in the brain, and these channels are next to each other and the probe is otherwise free of noise, that probe will still be sorted?

**Comment by alejoe91** [comment]
Hi, that's a very good idea. Do you suggest using something like `min_good_channels = 100`?

The reasoning to use a fraction was that ideally the same pipeline could be applied to lower-channel-count probes, like 64/128 channels. 

Alternatively, we could be less restrictive on the fraction of bad channels, e.g., `max_bad_channel_fraction_to_remove=0.8`? This would effectively mean that you can sort with more than 75 channels. Or we remove this check completely.

@jsiegle @bjhardcastle thougths?

**Comment by alejoe91** [comment]
Added an option to remove or not bad/out channels and to set the `max_bad_channel_fraction` via CLI inputs:
https://github.com/AllenNeuralDynamics/aind-ephys-spikesort-kilosort25-full/pull/19/files#diff-91af2d9cee71c20d36a2f42a2ebc7b3004890b3e23b9012fcc1c39f90576a65eR85-R108
